server:
  port: 12110
  servlet:
    context-path: "/lamp/lantern/service/core"

dubbo:
  application:
    name: lamp-lantern-core-consumer
    owner: dome

  provider:
    timeout: 30000
    retries: 0

  registry:
    address: N/A
    register: false
    subscribe: true


decoration:
   defaultExceptionResult: com.test.consumer.utils.VaastExceptionResult